language: python
python:
- '2.7'
script:
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- tar zxf dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- source dx-toolkit/environment
- dx find projects
env:
  global:
    secure: F9lvxdWotkstJlNNjYAjFwf1RvU8lHd12U2Bq3CmQS09gNKPRNUQy68pch9qUIIyC0FHvHlZWhRbG8Z4e7Cu1hvEeO/K5UcUThuV2R+4EuZtl7d8DAdivLgl/tbueW/kD8xvRfjainWfKj39W3srJ01LhTl4PjtcqYYx0bPLIK0=
