language: python
python:
- '2.7'
script:
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- tar zxf dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- source dx-toolkit/environment
- find . -type f
#env:
#  global:
#    secure: q8M16jIP5uoo9A+KFiKzPSzsHvO0SMey55upbd1v5YG3aNS3lN7Ix8qtPHbtev6uE7tW94Tn0tkIiMdVUhgfylC+nSwBAfNqEznZxq+FE3lBYnkHz5QPwEWe3DD3d8QrpknKZjc2jDWxDDELFotL5Ey7n9vSCdiE2HBQZFe7S60=
