language: python
python:
- '2.7'
script:
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- tar zxf dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- source dx-toolkit/environment
- dx find projects
env:
  global:
    secure: QPZ3kdlFOmvKAdqPqrUvx7Sv6495KcYQqV5h7xKia0LORpHkaY171zdSljKIit0KhdtO8vimRMTkWnUkJC/IMAueTriV6fOrt//zVIlxKnC6Pu/ffQsuMxK2Jv9XzBak7cRILDFygGNl8TNkWR3rKmFFDpF750PT3C/nqyFbKnE=
