language: python
python:
- '2.7'
script:
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- tar zxf dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- source dx-toolkit/environment
- echo "$DX_SECURITY_CONTEXT"
- dx find projects
env:
  global:
  - secure: BdDLPQE1yEiPrJGBSOMdkpL4Ua9x8VumbpR2vmvb3tid/EcquEUMthPSrH9NL8yK5/6M4U66kduY56VDhEfgy4PLviNyVqxWI5ZloQTvECFTAkNCOgm9smaoJ8kX8gHdvLLACCGfc0LNdYIRfvBT+Ie0jHyFNMGx0KIqDQkJU60=
